version: "3.5"
services:
  app:
    build: .
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    command: ['yarn', 'migrate-with-test']
    volumes:
      - type: bind
        source: .
        target: /home/app
    environment:
      - DB_USER=admin
      - DB_PWD=Sparks123
      - DB_HOST=mongo
      - DB_PORT=27017
    container_name: app

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # volumes:
      # - ./data:/data/db
    container_name: db
